name: Build and Deploy Image

on:
  release:
    types: [published]
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and publish
        pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: kzdv/api-docs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          no_push: ${{ github.event_name == "push" }}
      - name: Deploy image to cluster
        pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        if: ${{ github.event_name != "push" }}
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECTL }}
          TAG: ${ GITHUB_SHA::6 }
        with:
          args: set image deployment/api-docs api-docs=kzdv/api-docs:${{ env.TAG }} -n prod
      - name: Verify deployment
        if: ${{ github.event_name != "push" }}
        uses: actions-hub/kubectl@master
        with:
          args: rollout status deployment/api-docs
